# Generated by Django 4.2.13 on 2024-05-15 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songmanager', '0002_alter_usersong_atmospheres_alter_usersong_emotions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('playlist_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songmanager.user')),
            ],
        ),
    ]
