# Generated by Django 4.2.13 on 2024-05-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songmanager', '0003_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersong',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
