# Generated by Django 4.2.13 on 2024-05-18 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songmanager', '0004_alter_usersong_rating_delete_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energy',
            old_name='rating',
            new_name='energy',
        ),
    ]
