# Generated by Django 4.2.13 on 2024-05-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songmanager', '0006_alter_usersong_energy_delete_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='quick_add_option',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=20),
        ),
    ]
