# Generated by Django 4.2.13 on 2024-05-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songmanager', '0007_playlist_quick_add_option_alter_tag_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, to='songmanager.song'),
        ),
        migrations.AddField(
            model_name='usersong',
            name='playlists',
            field=models.ManyToManyField(blank=True, to='songmanager.playlist'),
        ),
    ]
