# Generated by Django 4.2.13 on 2024-05-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songmanager', '0009_alter_usersong_last_skipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersong',
            name='last_played',
            field=models.DateTimeField(null=True),
        ),
    ]
