# Generated by Django 4.2.13 on 2024-05-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songmanager', '0010_usersong_last_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='std_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
