# Generated by Django 4.2.13 on 2024-05-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songmanager', '0012_album_song_album_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
    ]
