# Generated by Django 4.2.13 on 2024-05-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songmanager', '0013_remove_song_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='smart_playlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='quick_add_option',
            field=models.BooleanField(default=False),
        ),
    ]
