# Generated by Django 4.2.13 on 2024-05-27 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songmanager', '0015_playlist_created_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='in_folder',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('playlists', models.ManyToManyField(blank=True, to='songmanager.playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songmanager.user')),
            ],
        ),
    ]
