# Generated by Django 4.2.13 on 2024-05-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songmanager', '0016_playlist_in_folder_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='smart_folder',
            field=models.BooleanField(default=False),
        ),
    ]
